services:
  - type: static
    name: resume-match-frontend
    env: node
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Installing dependencies..."
      npm install
      echo "Building application..."
      npm run build
      echo "Build complete. Contents of out directory:"
      ls -la out
    staticPublishPath: out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://resume-match-backend.onrender.com 