services:
  - type: web
    name: resume-match-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: static
          name: resume-match-frontend
          property: url

  - type: static
    name: resume-match-frontend
    env: node
    buildCommand: cd client && npm install && npm run build && npm run export
    staticPublishPath: client/out
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: resume-match-backend
          property: url
      - key: NODE_ENV
        value: production 