services:
  - type: web
    name: resume-match-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://resume-match-frontend.onrender.com

  - type: static
    name: resume-match-frontend
    env: node
    rootDir: client
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Installing dependencies..."
      npm install
      echo "Building application..."
      npm run build
      echo "Build complete. Contents of out directory:"
      ls -la out
    staticPublishPath: out
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://resume-match-backend.onrender.com 