services:
  - type: web
    name: resume-match-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://resume-match-frontend.onrender.com

  - type: static
    name: resume-match-frontend
    env: node
    buildCommand: |
      #!/bin/bash
      echo "Current directory: $(pwd)"
      echo "Listing contents:"
      ls -la
      echo "Changing to client directory..."
      cd client
      echo "Client directory contents:"
      ls -la
      echo "Installing dependencies..."
      npm install
      echo "Building..."
      npm run build
      echo "Exporting..."
      npm run export
    staticPublishPath: client/out
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://resume-match-backend.onrender.com 