services:
  - type: web
    name: resume-match-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://resume-match-frontend.onrender.com

  - type: static
    name: resume-match-frontend
    env: node
    rootDir: client
    buildCommand: npm install && npm run build && npm run export
    staticPublishPath: out
    envVarGroup: ResumeMatchApp
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://resume-match-backend.onrender.com 